export enum QueryAction {
  SET_SHEET_INDEX = 'SET_SHEET_INDEX',
  SET_INCLUDE_COLUMNS = 'SET_INCLUDE_COLUMNS',
  SET_FILTER_CONDITIONS = 'SET_FILTER_CONDITIONS',
  SET_QUERY_RESPONSE = 'SET_QUERY_RESPONSE',
  SET_QUERY_IN_PROGRESS = 'SET_QUERY_IN_PROGRESS',
  TOGGLE_RESET = 'TOGGLE_RESET',
  CLEAR = 'CLEAR'
}
